version: '3'
services:
  admin-center:
    container_name: admin-center
    ports:
      - "3200:3000"
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    networks:
      - deploy-dev_default
#    volumes:
#        - ./.next:/app/.next
networks:
  deploy-dev_default:
    name: deploy-dev_default